### ISSUE TITLE
[#45] Bug: Vote buttons and score disappears after upvoting and downvoting

### ISSUE THREAD

**Issue by PWatine** [Software-Process/Software-Process.github.io#173] opened 2018-03-21 18:53 UTC
Priority: Medium
Steps:
1.  Log in as a user (username: test7     password: test7)
2.  Click on a random question with 1 or more answers.
3. Upvote the question.
4. Downvote the question.
  Expected result: The score should return to the same value as it was when the page was loaded.
  Observed result: The score and the upvote/downvote arrows disappear.
5. Upvote an answer.
6. Downvote that very same answer.
  Expected result: The score should return to the same value as it was when the page was loaded.
  Observed result: The score and the upvote/downvote arrows of the answer disappears.

**Comment by dfeokti** [comment] 2018-03-21 21:45
Seems like a local issue, I can't reproduce it. Anyone else have the same issue?

**Comment by Michael-Gagnon** [comment] 2018-03-22 02:06
Same, discussed with other members of the team and this may be a local issue

**Comment by dfeokti** [comment] 2018-03-22 02:10
Closed as we cannot reproduce.

**Closed by dfeokti** 2018-03-22 02:10 UTC
Labels: Bug, CSS, HTML, JavaScript
